-- Snowflake Keypair Manager — Teardown script
-- Removes all objects created by deploy.sql. USE WITH CAUTION.

-- Suspend tasks first
ALTER TASK IF EXISTS SECURITY_OPS.KEYPAIR_MGMT.EXPIRY_MONITOR_TASK SUSPEND;
ALTER TASK IF EXISTS SECURITY_OPS.KEYPAIR_MGMT.AUTO_GRANT_TASK SUSPEND;

-- Drop tasks
DROP TASK IF EXISTS SECURITY_OPS.KEYPAIR_MGMT.EXPIRY_MONITOR_TASK;
DROP TASK IF EXISTS SECURITY_OPS.KEYPAIR_MGMT.AUTO_GRANT_TASK;

-- Drop procedures
DROP PROCEDURE IF EXISTS SECURITY_OPS.KEYPAIR_MGMT.CHECK_KEY_EXPIRY(INT, STRING);
DROP PROCEDURE IF EXISTS SECURITY_OPS.KEYPAIR_MGMT.AUTO_GRANT_KEYPAIR_ADMIN();

-- Drop integration
DROP NOTIFICATION INTEGRATION IF EXISTS keypair_mgmt_notifications;

-- Drop schema and database (optional — uncomment if you want full removal)
-- DROP SCHEMA IF EXISTS SECURITY_OPS.KEYPAIR_MGMT;
-- DROP DATABASE IF EXISTS SECURITY_OPS;

-- Drop role (optional — will revoke all grants)
-- DROP ROLE IF EXISTS KEY_PAIR_ADMIN;
